

listing_key_list = ["agents",
                    "description",
                    "createdOn",
                    "domainSays",
                    "features",
                    "id",
                    "inspection",
                    "isLandEstate",
                    "isRetirement",
                    "isStandardListing",
                    "listingSummary",
                    "listingType",
                    "listingUrl",
                    "locationProfileCards",
                    "map",
                    "otherListingsIds",
                    "primaryPropertyType",
                    "suburb",
                    "unitNumber",
                    "suburbInsights"
                    ]

listing_required_values = {"agent_name":"agents..0..name",
                            "agent_mobile":"agents..0..mobile",
                            "agent_email":"agents..0..email",
                            "description": "description",
                            "listing_createdOn": "createdOn",
                            "firstListedDate": "domainSays..firstListedDate",
                            "lastSoldOnDate": "domainSays..lastSoldOnDate",
                            "medianRentPrice": "domainSays..medianRentPrice",
                            "numberSold": "domainSays..numberSold",
                           "soldPropertiesUrl": "domainSays..soldPropertiesUrl",
                           "updatedDate": "domainSays..updatedDate",
                           "storyPropertyType": "domainSays..storyPropertyType",
                           "features": "features",
                           "id": "id",
                           "beds": "listingSummary..beds",
                            "baths": "listingSummary..baths",
                           "parking": "listingSummary..parking",
                           "title": "listingSummary..title",
                           "price": "listingSummary..price",
                           "address": "listingSummary..address",
                           "promoType": "listingSummary..promoType",
                           "stats": "listingSummary..stats",
                           "propertyType": "listingSummary..propertyType",
                           "status": "listingSummary..status",
                           "mode": "listingSummary..mode",
                           "method": "listingSummary..method",
                           "isRural": "listingSummary..isRural",
                           "listingType": "listingType",
                           "listingUrl": "listingUrl",
                            "location_profiles_list": "locationProfileCards..profiles",
                            "map_apiKey": "map..apiKey",
                           "map_latitude": "map..latitude",
                           "map_longitude": "map..longitude",
                           "map_suburbProfileUrl": "map..suburbProfileUrl",
                           "otherListingsIds_list": "otherListingsIds",
                           "primaryPropertyType": "primaryPropertyType",
                           "suburbInsights_beds": "suburbInsights..beds",
                           "suburbInsights_propertyType": "suburbInsights..propertyType",
                           "suburbInsights_medianPrice": "suburbInsights..medianPrice",
                           "suburbInsights_medianRentPrice": "suburbInsights..medianRentPrice",
                           "suburbInsights_auctionClearance": "suburbInsights..auctionClearance",
                           "suburbInsights_nrSoldThisYear": "suburbInsights..nrSoldThisYear",
                           "suburbInsights_entryLevelPrice": "suburbInsights..entryLevelPrice",
                           "suburbInsights_avgDaysOnMarket": "suburbInsights..avgDaysOnMarket",
                           "suburbInsights_luxuryLevelPrice": "suburbInsights..luxuryLevelPrice",
                           "suburbInsights_renterPercentage": "suburbInsights..renterPercentage",
                           "suburbInsights_singlePercentage": "suburbInsights..singlePercentage",
                           "suburbInsights_population": "suburbInsights..demographics..population",
                           "suburbInsights_avgAge": "suburbInsights..demographics..avgAge",
                           "suburbInsights_owners": "suburbInsights..demographics..owners",
                           "suburbInsights_renters": "suburbInsights..demographics..renters",
                           "suburbInsights_families": "suburbInsights..demographics..families",
                           "suburbInsights_singles": "suburbInsights..demographics..singles"
                           }