

listing_key_list = ["agents",
                    "description",
                    "createdOn",
                    "domainSays",
                    "features",
                    "id",
                    "inspection",
                    "isLandEstate",
                    "isRetirement",
                    "isStandardListing",
                    "listingSummary",
                    "listingType",
                    "listingUrl",
                    "locationProfileCards",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""
                    ]